version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=crud_vpt
      - MYSQL_USER=php_docker
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./devcontainer:/docker-entrypoint-initdb.d"

  www:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - 8000:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306